version: "3.8"

services:
  #nginx
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  #app
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      network: host
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  #mysql
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8088:80"

volumes:
  mysql_data:
